### ISSUE TITLE
about phsion++

### ISSUE THREAD

**Issue by shaa0066** [zfchenUnique/zfchenUnique.github.io#1]
Recently I read the paper of phsion++ and tried to reproduce the code.However,it seems that start_frame_for_prediction of the train_data and the True/False label for the readout_data are not given, which I thought I could find in the beginning. I went to see the work of physion and found it has True/False label for every data. How should I define the start_frame_for_prediction and train the map from dynamic representation to YES/NO of the OCP task?

**Comment by zfchenUnique** [comment]
Close issue since it has no relation to my homepage repo.
